import { chromium } from "playwright";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 2400 } });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const p = await ctx.newPage();
await p.goto("http://127.0.0.1:8777/index.html", { waitUntil: "commit", timeout: 8000 });
await p.waitForTimeout(4000);
await p.screenshot({ path: "landing/shot-full.png", fullPage: true, timeout: 15000 });
await b.close();
console.log("done");
